import type { PipelineResult } from '../core/pipeline.ts';
import type { Finding, FindingGroup, Severity } from '../core/finding.ts';

const PRIORITIES: readonly Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

export function renderMarkdownReport(result: PipelineResult): string {
  const out: string[] = [];
  const allFindings = [...result.consensus.groups.flatMap((g) => g.members), ...result.consensus.unique];
  const agreedCount = result.consensus.groups.length;
  const uniqueCount = result.consensus.unique.length;

  out.push(`# 🧭 Quorum review — ${escapeMd(result.pipelineId)}`);
  out.push('');
  out.push(
    [
      `**${result.reviews.length} reviewer(s)**`,
      `**${allFindings.length} finding(s)**`,
      `**${agreedCount} agreement group(s)**`,
      `**${uniqueCount} single-reviewer finding(s)**`,
      `**${result.errors.length} error(s)**`,
      `**${formatDuration(result.durationMs)}**`,
    ].join(' · '),
  );
  out.push('');
  out.push('## 📊 Summary');
  out.push('');
  out.push('| Severity | Findings |');
  out.push('| --- | ---: |');
  for (const severity of PRIORITIES) {
    out.push(`| ${severityIcon(severity)} ${severityLabel(severity)} | ${countSeverity(allFindings, severity)} |`);
  }
  out.push('');

  if (result.errors.length > 0) {
    out.push('## 🚨 Reviewer errors');
    for (const e of result.errors) out.push(`- **${escapeMd(e.reviewerId)}**: ${escapeMd(e.message)}`);
    out.push('');
  }

  out.push('## 🔎 Findings by priority');
  renderPriorityFindings(out, result.consensus.groups, result.consensus.unique);

  out.push('');
  out.push('---');
  out.push(`*Generated by quorum · consensus strategy: ${escapeMd(result.consensus.strategyId)}*`);
  return out.join('\n');
}

function renderPriorityFindings(out: string[], groups: FindingGroup[], unique: Finding[]): void {
  if (groups.length === 0 && unique.length === 0) {
    out.push('_No findings._');
    return;
  }

  for (const priority of PRIORITIES) {
    const priorityGroups = groups
      .filter((g) => g.representative.severity === priority)
      .sort((a, b) => b.reviewers.length - a.reviewers.length);
    const priorityUnique = unique.filter((f) => f.severity === priority);
    if (priorityGroups.length === 0 && priorityUnique.length === 0) continue;

    out.push(`### ${severityIcon(priority)} ${severityLabel(priority)} (${priorityGroups.length + priorityUnique.length})`);
    for (const g of priorityGroups) renderGroup(out, g);
    for (const f of priorityUnique) renderFinding(out, f);
  }
}

function renderGroup(out: string[], g: FindingGroup): void {
  const f = g.representative;
  out.push(`#### 🤝 ${escapeMd(f.title)}`);
  out.push('');
  out.push(`> ${g.reviewers.length} reviewer(s) agreed · ${g.members.length} matching report(s)`);
  out.push('');
  renderFindingMeta(out, f, `**Reviewers:** ${g.reviewers.map(escapeMd).join(', ')}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function renderFinding(out: string[], f: Finding): void {
  out.push(`#### 👤 ${escapeMd(f.title)}`);
  out.push('');
  renderFindingMeta(out, f, `**Reviewer:** ${escapeMd(f.reviewer)}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function renderFindingMeta(out: string[], f: Finding, reviewerLine: string): void {
  out.push(`- **Location:** \`${escapeFilePath(f.file)}:${f.lineRange.start}-${f.lineRange.end}\``);
  out.push(`- **Category:** ${categoryIcon(f.category)} ${f.category}`);
  out.push(`- ${reviewerLine}`);
}

function countSeverity(findings: Finding[], severity: Severity): number {
  return findings.filter((f) => f.severity === severity).length;
}

function severityIcon(s: Severity): string {
  switch (s) {
    case 'critical': return '🚨';
    case 'high': return '🔥';
    case 'medium': return '⚠️';
    case 'low': return '🧊';
    case 'info': return 'ℹ️';
  }
}

function severityLabel(s: Severity): string {
  return s[0]!.toUpperCase() + s.slice(1);
}

function categoryIcon(category: Finding['category']): string {
  switch (category) {
    case 'security': return '🔐';
    case 'performance': return '⚡';
    case 'architecture': return '🏗️';
    case 'correctness': return '✅';
    case 'style': return '🎨';
  }
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function escapeFilePath(p: string): string {
  return p.replace(/`/g, '\\`');
}

function escapeMd(s: string): string {
  return s.replace(/([\\`*_{}[\]()#+\-.!~|<>])/g, '\\$1');
}
