import type { PipelineResult } from '../core/pipeline.ts';
import type { Finding } from '../core/finding.ts';
import { severityRank } from '../core/finding.ts';

export function renderMarkdownReport(result: PipelineResult): string {
  const out: string[] = [];
  out.push(`# Quorum review — ${result.pipelineId}`);
  out.push('');
  out.push(`*${result.reviews.length} reviewer(s), ${result.errors.length} error(s), ${result.durationMs}ms*`);
  out.push('');

  if (result.errors.length > 0) {
    out.push('## Errors');
    for (const e of result.errors) out.push(`- **${e.reviewerId}**: ${e.message}`);
    out.push('');
  }

  out.push('## Consensus findings');
  const groups = [...result.consensus.groups].sort(
    (a, b) =>
      severityRank(b.representative.severity) - severityRank(a.representative.severity) ||
      b.reviewers.length - a.reviewers.length,
  );
  if (groups.length === 0) {
    out.push('_No findings raised by multiple reviewers._');
  } else {
    for (const g of groups) {
      const f = g.representative;
      out.push(`### [${g.reviewers.length} agreed] ${escapeMd(f.title)}`);
      out.push(`- **File:** \`${f.file}:${f.lineRange.start}-${f.lineRange.end}\``);
      out.push(`- **Severity:** ${f.severity}`);
      out.push(`- **Category:** ${f.category}`);
      out.push(`- **Reviewers:** ${g.reviewers.join(', ')}`);
      out.push('');
      if (f.body) out.push(escapeMd(f.body));
      out.push('');
    }
  }

  const unique = result.consensus.unique;
  if (unique.length > 0) {
    out.push('## Single-reviewer findings');
    const sorted = [...unique].sort((a, b) => severityRank(b.severity) - severityRank(a.severity));
    for (const f of sorted) renderFinding(out, f);
  }

  out.push('');
  out.push('---');
  out.push(`*generated by quorum (strategy: ${result.consensus.strategyId})*`);
  return out.join('\n');
}

function renderFinding(out: string[], f: Finding): void {
  out.push(`### ${escapeMd(f.title)} — ${f.severity}`);
  out.push(`- **File:** \`${f.file}:${f.lineRange.start}-${f.lineRange.end}\``);
  out.push(`- **Category:** ${f.category}`);
  out.push(`- **Reviewer:** ${f.reviewer}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function escapeMd(s: string): string {
  return s.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
