import type { PipelineResult } from '../core/pipeline.ts';
import type { Finding, FindingGroup, Severity } from '../core/finding.ts';

const PRIORITIES: readonly Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

export function renderMarkdownReport(result: PipelineResult): string {
  const out: string[] = [];
  out.push(`# Quorum review — ${escapeMd(result.pipelineId)}`);
  out.push('');
  out.push(`*${result.reviews.length} reviewer(s), ${result.errors.length} error(s), ${result.durationMs}ms*`);
  out.push('');

  if (result.errors.length > 0) {
    out.push('## Errors');
    for (const e of result.errors) out.push(`- **${escapeMd(e.reviewerId)}**: ${escapeMd(e.message)}`);
    out.push('');
  }

  out.push('## Findings by priority');
  renderPriorityFindings(out, result.consensus.groups, result.consensus.unique);

  out.push('');
  out.push('---');
  out.push(`*generated by quorum (strategy: ${escapeMd(result.consensus.strategyId)})*`);
  return out.join('\n');
}

function renderPriorityFindings(out: string[], groups: FindingGroup[], unique: Finding[]): void {
  if (groups.length === 0 && unique.length === 0) {
    out.push('_No findings._');
    return;
  }

  for (const priority of PRIORITIES) {
    const priorityGroups = groups
      .filter((g) => g.representative.severity === priority)
      .sort((a, b) => b.reviewers.length - a.reviewers.length);
    const priorityUnique = unique.filter((f) => f.severity === priority);
    if (priorityGroups.length === 0 && priorityUnique.length === 0) continue;

    out.push(`### Priority: ${priority}`);
    for (const g of priorityGroups) renderGroup(out, g);
    for (const f of priorityUnique) renderFinding(out, f);
  }
}

function renderGroup(out: string[], g: FindingGroup): void {
  const f = g.representative;
  out.push(`#### [${g.reviewers.length} agreed] ${escapeMd(f.title)}`);
  out.push(`- **File:** \`${escapeFilePath(f.file)}:${f.lineRange.start}-${f.lineRange.end}\``);
  out.push(`- **Category:** ${f.category}`);
  out.push(`- **Reviewers:** ${g.reviewers.map(escapeMd).join(', ')}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function renderFinding(out: string[], f: Finding): void {
  out.push(`#### ${escapeMd(f.title)}`);
  out.push(`- **File:** \`${escapeFilePath(f.file)}:${f.lineRange.start}-${f.lineRange.end}\``);
  out.push(`- **Category:** ${f.category}`);
  out.push(`- **Reviewer:** ${escapeMd(f.reviewer)}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function escapeFilePath(p: string): string {
  return p.replace(/`/g, '\\`');
}

function escapeMd(s: string): string {
  return s.replace(/([\\`*_{}[\]()#+\-.!~|<>])/g, '\\$1');
}
